# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-14 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_emoji', '0002_auto_20180614_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
